using CodeIndex.Models;

namespace CodeIndex.Indexer;

public partial class FileIndexer
{
    internal const string GeneratedCodeExtractionSkippedIssueKind = "generated_code_extraction_skipped";
    private const int GeneratedCodeHeaderScanLimitChars = 16 * 1024;

    internal static bool IsGeneratedCodeFile(string relativePath, string content)
        => HasGeneratedCodeFileName(relativePath) || HasGeneratedCodeHeader(content);

    internal bool IsGeneratedCodeExtractionSuppressed(string relativePath)
        => _generatedCodePatterns.TryMatch(relativePath, out _);

    internal FileIssue? BuildGeneratedCodeExtractionSkippedIssue(string relativePath)
        => IsGeneratedCodeExtractionSuppressed(relativePath)
            ? new FileIssue
            {
                Path = relativePath,
                Kind = GeneratedCodeExtractionSkippedIssueKind,
                Line = 0,
                Message = "Generated-code extraction suppressed by project configuration; file content and chunks were indexed, but symbols and references were skipped.",
                Origin = "generated_code_pattern",
                Severity = FileIssue.SeverityInfo,
            }
            : null;

    private static bool HasGeneratedCodeFileName(string relativePath)
    {
        var fileName = Path.GetFileName(relativePath.AsSpan());
        return fileName.EndsWith(".Designer.cs".AsSpan(), StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".g.cs".AsSpan(), StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".g.dart".AsSpan(), StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".gen.go".AsSpan(), StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".generated.ts".AsSpan(), StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith("_pb.go".AsSpan(), StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith("_pb2.py".AsSpan(), StringComparison.OrdinalIgnoreCase);
    }

    private static bool HasGeneratedCodeHeader(string content)
    {
        if (!MayContainGeneratedCodeHeader(content))
            return false;

        var remaining = content.AsSpan(0, Math.Min(content.Length, GeneratedCodeHeaderScanLimitChars));
        for (var lineNumber = 0; lineNumber < 20 && !remaining.IsEmpty; lineNumber++)
        {
            var newlineIndex = remaining.IndexOf('\n');
            var line = newlineIndex < 0 ? remaining : remaining[..newlineIndex];
            if (GeneratedHeaderLineContainsMarker(line))
                return true;

            if (newlineIndex < 0)
                break;

            remaining = remaining[(newlineIndex + 1)..];
        }

        return false;
    }

    private static bool MayContainGeneratedCodeHeader(string content)
    {
        var remaining = content.AsSpan(0, Math.Min(content.Length, GeneratedCodeHeaderScanLimitChars));
        var scannedLength = 0;
        for (var lineNumber = 0; lineNumber < 20 && !remaining.IsEmpty; lineNumber++)
        {
            var newlineIndex = remaining.IndexOf('\n');
            if (newlineIndex < 0)
            {
                scannedLength += remaining.Length;
                break;
            }

            scannedLength += newlineIndex + 1;
            remaining = remaining[(newlineIndex + 1)..];
        }

        var header = content.AsSpan(0, scannedLength);
        return header.Contains("generated".AsSpan(), StringComparison.OrdinalIgnoreCase)
            || header.Contains("DO NOT EDIT".AsSpan(), StringComparison.OrdinalIgnoreCase);
    }

    private static bool GeneratedHeaderLineContainsMarker(ReadOnlySpan<char> line)
        => line.Contains("<auto-generated".AsSpan(), StringComparison.OrdinalIgnoreCase)
            || line.Contains("@generated".AsSpan(), StringComparison.OrdinalIgnoreCase)
            || (line.Contains("generated by".AsSpan(), StringComparison.OrdinalIgnoreCase)
                && line.Contains("DO NOT EDIT".AsSpan(), StringComparison.OrdinalIgnoreCase));
}
