using CodeIndex.Database;

namespace CodeIndex.Cli;

public static partial class QueryCommandRunner
{
    private sealed record StatusFieldExplanation(
        string FieldName,
        string Label,
        string ReadyText,
        string DegradedText,
        string Remediation,
        string? Meaning = null,
        string? Source = null,
        IReadOnlyList<string>? Dependencies = null,
        string? Interpretation = null)
    {
        public string EffectiveMeaning =>
            Meaning ?? $"{Label} describes the `{FieldName}` status contract.";

        public string EffectiveSource =>
            Source ?? "The source-generated `StatusResult` JSON contract and the status reader or runtime enricher that populates this field.";

        public IReadOnlyList<string> EffectiveDependencies =>
            Dependencies ?? Array.Empty<string>();

        public string EffectiveInterpretation =>
            Interpretation ?? $"Ready: {ReadyText} Degraded or absent: {DegradedText}";
    }

    private static readonly StatusFieldExplanation[] StatusReadinessFields =
    [
        new(
            "graph_table_available",
            "Reference graph table",
            "reference, caller, callee, impact, unused, and hotspot queries can read indexed reference edges.",
            "reference graph queries degrade to empty or incomplete results because the symbol_references table is missing.",
            "Run `cdidx index <projectPath>` to rebuild the graph-capable index."),
        new(
            "graph_data_current",
            "Reference graph generation",
            "all indexed reference rows belong to a complete current index generation.",
            "successful graph rows remain queryable, but one or more files failed and graph coverage is incomplete.",
            "Fix the per-file error reported in `last_failed_or_partial_index_run`, then rerun the same index command; do not rebuild unless separately required."),
        new(
            "reference_graph_complete",
            "Reference extraction coverage",
            "reference-extraction cap state is available, current dynamic-language extractor contracts are stamped, and extraction completed without hitting a hard lookup or container-candidate safety cap.",
            "reference-extraction cap state is unavailable, a dynamic-language extractor stamp is stale, or one or more files hit a hard cap; absent graph edges are not authoritative.",
            "Inspect `reference_graph_incomplete_reasons` and `reference_extraction_cap_hits.state_available`: refresh indexing for unavailable state or stale contracts; for a hard cap, inspect `files`, reduce or exclude the generated/pathological source, and rerun indexing."),
        new(
            "issues_table_available",
            "Validation issues table",
            "the file_issues table exists in this index.",
            "validate output degrades to empty because the file_issues table is missing.",
            "Run `cdidx index <projectPath>` to rebuild the issue table."),
        new(
            "file_issues_data_current",
            "Validation issues data",
            "file_issues rows are stamped current for this index generation.",
            "file_issues rows may be stale or partial for this index generation.",
            "Run `cdidx index <projectPath>` to refresh file issue rows."),
        new(
            "migration_in_progress",
            "Migration/write state",
            "no index write or migration is currently in progress.",
            "an index write or migration is in progress, so readiness may be temporarily degraded.",
            "Wait for the active `cdidx index` run to finish, then rerun `cdidx status --json`."),
        new(
            "index_complete",
            "Index generation completeness",
            "the latest persisted index generation completed every candidate file without a symbol-kind coverage filter.",
            "one or more files failed, a persisted symbol-kind filter intentionally limited coverage, or legacy filter provenance is unavailable.",
            "Inspect `index_incomplete_reasons`: fix structured file failures and rerun the same command, or rebuild without `--include-symbol-kind` / `--exclude-symbol-kind` when authoritative negative symbol and graph results are required."),
        new(
            "symbol_kind_filter_provenance_available",
            "Persisted symbol-kind policy provenance",
            "the normalized include/exclude policy for this persisted generation is available.",
            "the DB predates persisted policy provenance, so negative symbol and graph results are conservatively non-authoritative.",
            "Run `cdidx index <projectPath> --rebuild` with a current binary to stamp an explicit unfiltered or filtered policy."),
        new(
            "symbol_kind_filter",
            "Persisted symbol-kind policy",
            "the object publishes normalized `include` and `exclude` lists; empty lists mean an unfiltered generation.",
            "a non-empty list intentionally limits generation coverage even when `symbols_dropped_by_kind_filter` is zero.",
            "Rebuild without the symbol-kind options when full symbol and graph absence authority is required."),
        new(
            "symbols_dropped_by_kind_filter",
            "Persisted symbol-kind drop count",
            "zero means the persisted per-file audit facts recorded no dropped symbols for this generation.",
            "a positive value counts symbols intentionally removed by the persisted kind policy; absence means the legacy DB has no per-file audit column.",
            "Use the count for bounded audit evidence and inspect `symbol_kind_filter`; rebuild unfiltered for authoritative negative queries."),
        new(
            "sql_graph_contract_ready",
            "SQL graph contract",
            "SQL reference/dependency rows were written with the current call-column and qualified-name contract.",
            "SQL graph/dependency readers may return stale or incomplete results.",
            "Run `cdidx index <projectPath>` to rewrite SQL graph rows."),
        new(
            "hotspot_family_ready",
            "Hotspot family contract",
            "cross-file hotspot family grouping is stamped for all supported languages in this index.",
            "cross-file hotspot grouping may be degraded for one or more languages.",
            "Run `cdidx index <projectPath> --rebuild` to restamp authoritative hotspot families for every indexed row."),
        new(
            "csharp_symbol_name_ready",
            "C# symbol-name contract",
            "C# exact-name lookup uses authoritative persisted names for operators, conversions, and indexers.",
            "C# exact-name lookup for operators, conversions, and indexers may fall back to older canonical names.",
            "Run `cdidx index <projectPath>` to upgrade canonical C# symbol names."),
        new(
            "csharp_metadata_target_ready",
            "C# metadata target contract",
            "deps and impact use authoritative C# metadata-attribute targets.",
            "deps and impact metadata-attribute edges fall back to legacy signature/name heuristics.",
            "Run `cdidx index <projectPath>` to restamp authoritative C# metadata targets."),
        new(
            "fold_ready",
            "Unicode exact-name fold contract",
            "--exact-name can use Unicode NFKC + CaseFold equality.",
            "--exact-name falls back to ASCII COLLATE NOCASE, so non-ASCII casing pairs may not match.",
            "Run `cdidx backfill-fold` to restamp folded-name columns in place, or `cdidx index <projectPath> --rebuild` for a full rebuild."),
        new(
            "index_newer_than_reader",
            "Reader compatibility",
            "this cdidx binary understands all persisted index contract versions.",
            "this DB was written by a newer cdidx, so older readers may degrade instead of trusting newer contract stamps.",
            "Run status with a current cdidx binary, or rebuild the DB with the version you intend to use."),
    ];

    private static readonly StatusFieldExplanation[] StatusMemberExplainFields =
    [
        new(
            "reference_extraction_cap_hits.state_available",
            "Reference cap-hit state availability",
            "`true` means the current index generation persisted cap-hit audit state.",
            "`false` means graph absence cannot be treated as authoritative until indexing refreshes the audit state.",
            "Run `cdidx index <projectPath>` with a current binary, then recheck `reference_graph_complete`.",
            Meaning: "Identifies whether the cap-hit summary is backed by current persisted audit state.",
            Source: "The persisted reference-extraction completeness metadata read with the current index generation.",
            Dependencies: ["reference_extraction_cap_hits", "reference_graph_complete"],
            Interpretation: "Treat zero cap hits as authoritative only when this member is `true`."),
        new(
            "reference_extraction_cap_hits.files",
            "Reference cap-hit file sample",
            "the bounded list identifies files and stable cap reasons that limited reference extraction.",
            "an empty list is non-authoritative when `state_available=false`, and `files_truncated=true` means additional affected files were omitted.",
            "Inspect the listed files, reduce or exclude pathological/generated input, rerun indexing, and recheck graph readiness.",
            Meaning: "A bounded, support-safe sample of files whose reference extraction hit a safety cap.",
            Source: "Per-file cap diagnostics persisted by the reference extractor and summarized by the status reader.",
            Dependencies: ["reference_extraction_cap_hits.state_available", "reference_extraction_cap_hits.files_truncated", "reference_extraction_cap_hits.file_limit"],
            Interpretation: "Use the sample for diagnosis, not as an exhaustive inventory when truncation is reported."),
        new(
            "maintenance_guidance.wal_state",
            "Maintenance WAL state",
            "`ok` means WAL bytes are below the configured warning threshold.",
            "`checkpoint_recommended` suggests a bounded WAL checkpoint; `unknown` means the size could not be measured.",
            "Follow `maintenance_guidance.recommended_command` only after confirming no index writer is active.",
            Meaning: "Classifies the current WAL size against the effective maintenance warning threshold.",
            Source: "Live database/WAL metrics and `CDIDX_MAINTENANCE_WAL_WARN_BYTES` (or its default).",
            Dependencies: ["wal_size_bytes", "maintenance_guidance.wal_threshold_bytes"],
            Interpretation: "This is maintenance advice, not a readiness failure by itself."),
        new(
            "maintenance_guidance.recommended_command",
            "Recommended maintenance command",
            "`none` means the measured WAL and freelist metrics do not currently recommend maintenance.",
            "a command string recommends one operator action derived from the measured WAL/freelist state.",
            "Run the command only against the intended database and only when no index writer is active; then follow `post_maintenance_follow_up` when present.",
            Meaning: "The single maintenance action selected from the current WAL and freelist classifications.",
            Source: "The maintenance guidance builder using live PRAGMA/file metrics and configured thresholds.",
            Dependencies: ["maintenance_guidance.wal_state", "maintenance_guidance.freelist_state"],
            Interpretation: "Treat the command as operator guidance rather than an automatically executed action."),
        new(
            "maintenance_guidance.fts_optimization",
            "FTS optimization guidance",
            "the object reports the shared `recommended`, `action`, `reason`, `threshold_writes`, `observed_writes`, and `state` decision used by status and optimize.",
            "`state=stale` or `state=unavailable` suppresses an optimize recommendation because the persisted write counter or database-page snapshot is not trustworthy.",
            "Wait for active indexing to finish and rerun `cdidx status --json`; run `cdidx optimize --dry-run --json` to inspect the same decision before mutation.",
            Meaning: "A read-only recommendation for optimizing FTS indexes after enough incremental writes.",
            Source: "The shared maintenance guidance builder using the persisted incremental-write counter and current database-page snapshot.",
            Dependencies: ["maintenance_guidance.fts_optimization.state", "maintenance_guidance.fts_optimization.observed_writes"],
            Interpretation: "Run optimize only when `recommended=true` and the state is current."),
        new(
            "maintenance_guidance.fts_optimization.state",
            "FTS optimization snapshot state",
            "`current` means the recommendation uses a trustworthy persisted write counter and database-page snapshot.",
            "`stale` or `unavailable` suppresses recommendation even when the observed counter would otherwise reach the threshold.",
            "Wait for active indexing to finish and rerun status before acting on a stale or unavailable recommendation.",
            Meaning: "Trust state for the shared FTS optimization recommendation.",
            Source: "The maintenance snapshot lifecycle and persisted incremental-write counter.",
            Dependencies: ["maintenance_guidance.fts_optimization.recommended", "maintenance_guidance.fts_optimization.reason"],
            Interpretation: "Treat only `current` decisions as actionable."),
        new(
            "extractors.diagnostics",
            "Extractor diagnostics",
            "an absent or empty list means no bounded plugin/pattern discovery diagnostic was emitted.",
            "entries report stable categories for skipped, incompatible, malformed, or unsafe extractor inputs.",
            "Follow each sanitized diagnostic and rerun indexing after correcting or removing the affected extension input.",
            Meaning: "Bounded, sanitized diagnostics produced while discovering extractor plugins and pattern configurations.",
            Source: "The active workspace extractor registry snapshot.",
            Dependencies: ["extractors.diagnostic_count", "extractors.diagnostic_limit", "extractors.diagnostics_truncated"],
            Interpretation: "Use `diagnostics_truncated` to decide whether the returned list is exhaustive."),
        new(
            "extractors.registration_precedence",
            "Extractor registration precedence",
            "the list publishes the deterministic highest-first order used to resolve competing extractor registrations.",
            "an absent or unexpected order indicates a contract mismatch between the status reader and active registry.",
            "Use a current binary and remove unintended higher-precedence registrations before reindexing.",
            Meaning: "The fixed precedence order applied when built-in, user, and workspace extractors overlap.",
            Source: "The active immutable extractor registry snapshot.",
            Dependencies: ["extractors.snapshot_scope"],
            Interpretation: "Earlier entries win when more than one registration handles the same language or pattern."),
        new(
            "hooks.callback_budget_ms",
            "Hook callback budget",
            "the positive value is the per-callback time budget enforced for the current index run.",
            "a callback exceeding the budget is timed out, its scratch mutation is discarded, and only that hook ID is disabled for the run.",
            "Reduce hook work or adjust `CDIDX_HOOK_CALLBACK_BUDGET_MS` within the documented safe range, then rerun indexing.",
            Meaning: "The maximum elapsed time allowed for one post-extraction hook callback.",
            Source: "The sanitized hook discovery snapshot and effective callback-budget configuration.",
            Dependencies: ["hooks.id", "hook_diagnostics"],
            Interpretation: "The budget is enforced per hook callback, not as a total budget for the entire index run."),
        new(
            "hooks.assembly_path",
            "Hook assembly path",
            "the member identifies the sanitized assembly location associated with a discovered hook.",
            "the path is diagnostic context only and must not be treated as authorization to load arbitrary content.",
            "Correct the trusted hook directory or assembly permissions, then rerun discovery/indexing.",
            Meaning: "A support-safe path label for the assembly that owns the hook manifest entry.",
            Source: "The bounded hook discovery worker after trust validation and diagnostic sanitization.",
            Dependencies: ["hooks.id", "trust_overrides", "hook_diagnostics"],
            Interpretation: "Runtime values are never fetched by `--explain`; this explanation contains contract metadata only."),
        new(
            "trust_overrides.environment_variable",
            "Trust override environment variable",
            "the member names the accepted `CDIDX_*` variable that widened a specific executable-extension trust boundary.",
            "an absent `trust_overrides` section means no supported trust override was accepted.",
            "Unset the variable to return to the default trust boundary, or audit the paired sanitized value/path before continuing.",
            Meaning: "Names the environment variable responsible for one accepted trust override.",
            Source: "Accepted override snapshots from extractor, hook, and Git executable trust resolvers.",
            Dependencies: ["trust_overrides.kind", "trust_overrides.value", "trust_overrides.path"],
            Interpretation: "Presence records accepted authority; it is not merely a copy of all `CDIDX_*` environment variables."),
        new(
            "trust_overrides.path",
            "Trust override path",
            "the optional member is a sanitized support-safe path associated with the accepted override.",
            "absence means the override has no path target or no safe path can be reported.",
            "Audit the underlying local path and permissions outside exported status output before trusting executable content.",
            Meaning: "Provides redacted path context for a path-bearing accepted trust override.",
            Source: "Trust-boundary resolvers after path canonicalization and diagnostic sanitization.",
            Dependencies: ["trust_overrides.kind", "trust_overrides.environment_variable"],
            Interpretation: "The reported value is intentionally sanitized and may not be an absolute filesystem path."),
    ];

    private static readonly StatusFieldExplanation[] StatusExplainFields =
        StatusReadinessFields.Concat(
        [
            new(
                "reference_extraction_limits",
                "Reference extraction safety limits",
                "the section publishes the hard lookup, line, names-per-line, and container-candidate limits enforced by this binary.",
                "missing or mismatched limits make cap-hit interpretation incomplete for automation.",
                "Use a current binary and inspect `reference_extraction_cap_hits` before treating absent graph edges as authoritative.",
                Meaning: "Publishes the bounded-work limits that constrain reference extraction.",
                Source: "Compiled reference-extractor safety constants serialized with status.",
                Dependencies: ["reference_graph_complete", "reference_extraction_cap_hits"],
                Interpretation: "These are hard safety ceilings, not observed usage counts."),
            new(
                "reference_extraction_cap_hits",
                "Reference extraction cap hits",
                "`state_available=true` with `hit_count=0` means the current generation recorded no reference-extraction cap hit.",
                "unavailable state or positive hits make absent callers/callees/deps/impact edges non-authoritative.",
                "Inspect `reasons` and bounded `files`, correct pathological/generated input or refresh stale state, then rerun indexing.",
                Meaning: "Summarizes whether hard reference-extraction safety caps were reached and which files were affected.",
                Source: "Persisted per-file reference-extraction diagnostics summarized for the current index generation.",
                Dependencies: ["reference_extraction_limits", "reference_graph_complete", "reference_graph_incomplete_reasons"],
                Interpretation: "Check `state_available` before interpreting zero hits, and check `files_truncated` before treating the file list as exhaustive."),
            new(
                "language_readiness",
                "Per-language readiness",
                "each language/family entry reports whether its persisted contract is authoritative for the current generation.",
                "a `ready=false` member narrows degradation to the named language and contract family.",
                "Follow the matching top-level degraded reason/action and rerun the required index or backfill operation.",
                Meaning: "Groups readiness signals by indexed language and contract family.",
                Source: "Persisted contract stamps evaluated by the status reader.",
                Dependencies: ["hotspot_family_ready", "csharp_symbol_name_ready", "csharp_metadata_target_ready"],
                Interpretation: "Use this section to localize a top-level readiness failure; it does not replace the top-level compatibility fields."),
            new(
                "workspace_check",
                "Workspace freshness details",
                "a matching check accounts for indexed, changed, missing, outside-sparse-cone, unindexed, unverifiable, and scan-error files.",
                "non-matching counts and bounded file lists explain why `index_matches_workspace=false`.",
                "Run the status-provided repair command or `cdidx index <projectPath>`, then repeat `status --check --json`.",
                Meaning: "Detailed result of the optional workspace-to-index freshness comparison.",
                Source: "A bounded live workspace scan compared with persisted indexed file metadata.",
                Dependencies: ["index_matches_workspace", "query_context", "head_freshness"],
                Interpretation: "The section is emitted only when the workspace check runs; omitted lists must be interpreted with their counts/truncation metadata."),
            new(
                "repair_commands",
                "Status repair commands",
                "entries provide machine-readable commands scoped to failed checks.",
                "absence means no check-specific repair command was generated, not that every optional maintenance action is unnecessary.",
                "Review each command, safety note, project/database target, and rebuild flag before execution.",
                Meaning: "Bounded remediation commands generated for the failed `status --check` scopes.",
                Source: "The status-check failure set and command builders for each readiness contract.",
                Dependencies: ["failed_checks", "workspace_check", "readiness_degradations"],
                Interpretation: "Commands are guidance and are never executed by `status`."),
            new(
                "readiness_degradations",
                "Readiness degradation inventory",
                "an absent list means no tracked readiness field is degraded.",
                "each entry records the degraded field, stable root cause, human reason, and remediation.",
                "Follow the highest-priority applicable action, then rerun status to confirm every degradation cleared.",
                Meaning: "Lists every currently degraded readiness contract rather than only the primary summary.",
                Source: "Top-level readiness fields evaluated by the shared degradation registry.",
                Dependencies: ["degraded_root_cause", "degraded_reason", "recommended_action", "alternative_action"],
                Interpretation: "The first entry drives the primary top-level degradation fields; later entries remain independently actionable."),
            new(
                "extractors",
                "Extractor registry diagnostics",
                "the section describes the active immutable extractor snapshot, registration counts/precedence, lifecycle, skipped files, and bounded diagnostics.",
                "non-zero skipped/diagnostic counts or truncation identify extension inputs that were not fully accepted.",
                "Inspect sanitized diagnostics and pattern configuration entries, correct trust/compatibility problems, then rerun indexing.",
                Meaning: "Describes the extractor plugins and pattern configurations active for this workspace snapshot.",
                Source: "The workspace-scoped `ExtractorPluginRegistry` snapshot selected at status time.",
                Dependencies: ["trust_overrides", "graph_supported_languages"],
                Interpretation: "Registration counts describe accepted active registrations; diagnostics describe rejected or degraded candidates."),
            new(
                "hooks",
                "Post-extraction hook manifests",
                "entries describe hooks discovered in isolated workers with stable IDs, sanitized assembly/type context, callback budgets, and lifecycle.",
                "absence means no hook manifest was accepted; failures and timeouts appear in `hook_diagnostics`.",
                "Inspect `hook_diagnostics` and accepted trust overrides, correct the hook assembly/configuration, then rerun indexing.",
                Meaning: "Publishes accepted post-extraction hook manifests without executing callbacks during explanation.",
                Source: "Deadline-, memory-, and output-bounded hook discovery workers.",
                Dependencies: ["hook_diagnostics", "trust_overrides"],
                Interpretation: "Manifest presence does not prove every callback succeeded; correlate by assembly-qualified hook `id`."),
            new(
                "hook_diagnostics",
                "Post-extraction hook diagnostics",
                "an absent or empty list means discovery/indexing emitted no bounded hook diagnostic.",
                "entries use stable categories for discovery, construction, callback, timeout, and trust failures.",
                "Follow the sanitized diagnostic, correct or remove the affected hook, and rerun indexing.",
                Meaning: "Bounded, sanitized failures and warnings associated with hook discovery or callback execution.",
                Source: "Hook discovery workers and the current index run's callback runner.",
                Dependencies: ["hooks", "trust_overrides"],
                Interpretation: "Use `hook_id` when present to correlate a diagnostic with the corresponding hook manifest."),
            new(
                "trust_overrides",
                "Accepted trust overrides",
                "each entry records a supported trust-boundary override that was explicitly accepted after validation.",
                "absence means no supported override widened extractor, hook, Git, or GitHub CLI executable trust for this status snapshot.",
                "Audit the named environment variable and sanitized value/path; unset it to return to the default trust boundary.",
                Meaning: "Audits accepted environment overrides that authorize workspace plugins, hook directories, Git, or GitHub CLI executables.",
                Source: "Extractor, hook-directory, Git, and GitHub CLI executable trust resolvers after validation and sanitization.",
                Dependencies: ["extractors", "hooks", "git_executable", "github_cli_executable"],
                Interpretation: "Only accepted overrides appear; rejected candidates remain in their owning diagnostic section."),
            new(
                "db_pragma_settings",
                "Database PRAGMA settings",
                "the section reports the active journal, durability, checkpoint, timeout, page-count, freelist, page-size, and auto-vacuum settings.",
                "unexpected values can explain WAL growth, locking, durability, or maintenance behavior.",
                "Compare against the documented SQLite policy and reopen/reindex the intended database after correcting configuration.",
                Meaning: "A live snapshot of SQLite PRAGMA values relevant to status trust and maintenance.",
                Source: "The active status reader connection and database header/PRAGMA queries.",
                Dependencies: ["sqlite_connection_policy", "maintenance_guidance"],
                Interpretation: "Values describe this connection/database snapshot and can change after maintenance or reopening."),
            new(
                "prepared_command_cache",
                "Prepared-command cache metrics",
                "counts and capacity expose bounded cache occupancy, hits, misses, and evictions for the active reader.",
                "high misses/evictions can explain repeated query preparation but do not by themselves degrade correctness.",
                "No repair is normally required; use the metrics for performance diagnosis and rerun against a representative workload.",
                Meaning: "Runtime metrics for the bounded SQLite prepared-command cache.",
                Source: "The active database reader instance at status-call time.",
                Dependencies: ["process"],
                Interpretation: "Metrics are process-local and reset with a new reader/process."),
            new(
                "maintenance_guidance",
                "Database maintenance guidance",
                "`recommended_command=none` means measured WAL/freelist metrics are below their effective warning thresholds; `fts_optimization` reports the shared `recommended`, `action`, `reason`, `threshold_writes`, `observed_writes`, and `state` decision used by status and optimize.",
                "checkpoint/vacuum recommendations are advisory; `state=stale` or `state=unavailable` suppresses FTS optimization when its persisted counter or database-page snapshot is not trustworthy.",
                "Review the maintenance command and follow-up with no writer active; rerun status after indexing, and use `cdidx optimize --dry-run --json` before an FTS mutation.",
                Meaning: "Classifies WAL and freelist metrics, selects at most one bounded operator maintenance action, and publishes the shared FTS optimization recommendation.",
                Source: "Live database/WAL sizes, PRAGMA metrics, effective thresholds, and the persisted incremental-write counter.",
                Dependencies: ["db_pragma_settings", "db_size_bytes", "wal_size_bytes", "maintenance_guidance.fts_optimization"],
                Interpretation: "Guidance is advisory and never executes a maintenance command or FTS optimization."),
            new(
                "database_size_attribution",
                "Database size attribution",
                "`available=true` reconciles bounded physical and logical SQLite page/object size measurements.",
                "`available=false` includes a stable unavailable reason; omitted object-byte fields must not be interpreted as zero.",
                "Inspect the unavailable reason or largest bounded objects, then use supported maintenance commands if reclamation is appropriate.",
                Meaning: "Separates physical DB/WAL/SHM bytes and reconciles logical page ownership with bounded object samples.",
                Source: "Read-only SQLite dbstat/page queries and filesystem size observations.",
                Dependencies: ["db_size_bytes", "wal_size_bytes", "db_pragma_settings"],
                Interpretation: "Use `unexplained_residual_bytes` and availability metadata when reconciling totals."),
            new(
                "process",
                "Status process metrics",
                "the section reports heap, GC, and working-set metrics captured for the current process.",
                "large values are diagnostic observations and do not alone imply an index correctness failure.",
                "Reproduce with the same command/workload and use `last_index_run` memory data when investigating sustained pressure.",
                Meaning: "A point-in-time runtime memory/GC snapshot for the process serving status.",
                Source: "The .NET runtime and operating-system process APIs at status-call time.",
                Dependencies: [],
                Interpretation: "Metrics are ephemeral and should be compared across equivalent workloads."),
            new(
                "last_index_run",
                "Last successful index run",
                "the section records the most recent successful run's mode, timing, work counts, byte coverage, diagnostics, and optional peak memory.",
                "absence indicates a legacy database or missing run metadata; bounded diagnostics can mark best-effort metadata-write problems.",
                "Rerun indexing with a current binary to refresh the snapshot; use `--memory-trace` when peak-memory evidence is required.",
                Meaning: "A persisted audit snapshot of the last successful full or update index run.",
                Source: "Metadata stamped at the end of a successful CLI or MCP index operation.",
                Dependencies: ["last_workspace_freshened_at", "index_complete", "reference_extraction_cap_hits"],
                Interpretation: "This is historical run metadata, not live progress."),
            new(
                "last_failed_or_partial_index_run",
                "Last failed or partial index run",
                "absence means no persisted failed/partial run currently requires operator attention.",
                "presence records bounded per-file failures, persisted progress, and recovery guidance while successful data may remain queryable.",
                "Fix the structured file/extractor failures and rerun the same index command; do not rebuild unless the guidance says it is required.",
                Meaning: "A persisted audit snapshot of the most recent failed or partial index generation.",
                Source: "The index runner's bounded failure persistence path.",
                Dependencies: ["index_complete", "graph_data_current", "file_issues_data_current"],
                Interpretation: "Use `progress_persisted` to distinguish retained successful work from a fully rolled-back attempt."),
            new(
                "git_head",
                "Runtime Git HEAD",
                "the current workspace Git HEAD commit was resolved at status time.",
                "the field is absent outside a Git checkout or when Git HEAD cannot be resolved.",
                "Run inside a Git workspace or pass a database tied to a Git workspace to compare index stamps."),
            new(
                "git_is_dirty",
                "Runtime Git dirty state",
                "`true` means git status reported uncommitted changes, including untracked files; `false` means no changes were reported.",
                "the field is absent outside a Git checkout or when dirty-state detection is unavailable.",
                "Run `git status` in the workspace to inspect uncommitted changes directly."),
            new(
                "git_executable",
                "Trusted Git executable selection",
                "`accepted=true` means cdidx validated the absolute Git path, metadata type, owner/mode and ancestor trust, then successfully executed `git --version`.",
                "`accepted=false` includes a stable `reason` identifying the failed path, metadata, owner, mode, ancestor, or execution probe.",
                $"Set `{GitHelper.GitExecutableEnvironmentVariable}` to a trusted absolute `git` path (`git.exe` on Windows), then inspect the nested diagnostics again."),
            new(
                "github_cli_executable",
                "Trusted GitHub CLI executable selection",
                "`accepted=true` means cdidx validated the absolute GitHub CLI path, metadata type, owner/mode and ancestor trust, then successfully executed a bounded `gh --version` probe.",
                "`accepted=false` includes a stable `reason` identifying the failed path, metadata, owner, mode, ancestor, image, identity, or execution probe.",
                $"Install GitHub CLI in a standard location or set `{GitHubCliExecutableResolver.ExecutableEnvironmentVariable}` to a trusted absolute `gh` path (`gh.exe` on Windows), then inspect the nested diagnostics again."),
            new(
                "indexed_head_commit",
                "Legacy full-scan HEAD stamp",
                "the index records the Git HEAD from the most recent successful full scan for legacy compatibility.",
                "this full-scan-only stamp can differ from both verification and latest-write provenance after incremental indexing and may be absent in legacy or non-Git indexes.",
                "Prefer `workspace_verified_head_sha` for HEAD freshness; run `cdidx index <projectPath>` when only this compatibility stamp is available."),
            new(
                "workspace_verified_head_sha",
                "Whole-workspace verified HEAD",
                "the index records the Git HEAD whose complete tracked workspace was verified by a full scan or a baseline-reconciled Git refresh.",
                "the field is absent on legacy or non-Git indexes; explicit `--files` updates preserve a current value and carry affected paths into the next reconciled Git refresh but cannot advance an older value.",
                "Run `cdidx index <projectPath>` or a Git-scoped refresh whose new ref is the current HEAD to publish current whole-workspace verification."),
            new(
                "worktree_head_changed",
                "Worktree HEAD drift",
                "`false` means the runtime HEAD matches the whole-workspace verified HEAD; `true` means the checkout moved beyond verified coverage.",
                "the field is absent when neither `workspace_verified_head_sha` nor the legacy `indexed_head_commit` can be compared with runtime HEAD.",
                "Run `cdidx index <projectPath>` to refresh the index for the current checkout."),
            new(
                "indexed_head_sha",
                "Latest index HEAD stamp",
                "the index records the Git HEAD from the last successful index run, including incremental updates.",
                "the field is absent in legacy indexes, non-Git workspaces, or when the index run could not resolve HEAD.",
                "Use this field to audit latest-write provenance; use `workspace_verified_head_sha` for whole-workspace HEAD freshness."),
            new(
                "indexed_head_branch",
                "Latest index branch stamp",
                "the index records the branch short name captured with `indexed_head_sha`.",
                "the field is absent for detached HEAD, legacy indexes, non-Git workspaces, or unresolved branch names.",
                "Use it as context for `indexed_head_sha`; rerun `cdidx index <projectPath>` after switching branches."),
            new(
                "indexed_head_timestamp",
                "Latest index HEAD timestamp",
                "the index records when `indexed_head_sha` and `indexed_head_branch` were stamped.",
                "the field is absent in legacy indexes or when the index run could not persist the timestamp.",
                "Rerun `cdidx index <projectPath>` to refresh the timestamp with the current checkout."),
            new(
                "commits_ahead_of_indexed_head",
                "Commits ahead of indexed HEAD",
                "`0` means runtime HEAD is not ahead of `indexed_head_sha`; positive values mean the checkout advanced after indexing.",
                "the field is absent when Git comparison is unavailable or history is not comparable.",
                "Run `cdidx index <projectPath>` when the value is positive before trusting freshness-sensitive results."),
            new(
                "data_dir_mode",
                "Data directory mode",
                "the field reports the current cdidx data directory's Unix permission mode, such as `0700`, when the platform exposes it.",
                "the field is absent for URI databases, missing directories, platforms without Unix file modes, or readers that cannot inspect the directory.",
                "Use this field for support-safe permission audits; inspect the data directory locally when the field is absent or broader than expected."),
            new(
                "db_file_mode",
                "Database file mode",
                "the field reports the active database's Unix permission mode, such as `0600`, when cdidx can inspect it.",
                "the field is absent for URI databases, missing files, platforms without Unix file modes, or best-effort mode reads that produced a permission diagnostic.",
                "Inspect `database_permission_diagnostics`; move the database or correct its owner-only permissions when the mode cannot be read or is broader than expected."),
            new(
                "database_permission_policy",
                "Database permission policy",
                "`best_effort` keeps usable SQLite databases available while reporting Unix-mode hardening failures; `strict` requires every applicable mode operation to succeed.",
                "an invalid configured policy fails before the database opens, while strict mode fails with `database_permission_hardening_failed` when enforcement is unavailable.",
                $"Set `{DatabasePermissionPolicy.EnvironmentVariable}` to `{DatabasePermissionPolicy.BestEffortName}` (default) or `{DatabasePermissionPolicy.StrictName}` according to the filesystem and security requirement."),
            new(
                "database_permission_diagnostics",
                "Database permission diagnostics",
                "an absent field means no applicable Unix-mode operation failed during this database open and status read.",
                "entries identify the failed `operation`, database `target`, stable `reason`, support-safe message, and `recommended_action` without exposing the database path.",
                $"Follow each `recommended_action`, or set `{DatabasePermissionPolicy.EnvironmentVariable}={DatabasePermissionPolicy.StrictName}` when permission hardening must be mandatory."),
            new(
                StatusResult.SqliteConnectionPolicyJsonFieldName,
                "SQLite connection policy",
                "the object reports the active/open modes, pooling and immutable-URI choices, command timeout, cancellation requirement, and WAL snapshot-risk diagnostics used by this status read.",
                "read-only fallback or stale-snapshot risk fields identify when the preferred query-only connection path could not be used safely or may omit hot WAL content.",
                "Inspect the nested policy and WAL diagnostics; avoid explicit immutable mode for a hot WAL database, or rerun after the writer checkpoints and closes."),
            new(
                "unknown_extension_file_count",
                "Unknown extension inventory",
                "`0` means the last successful full scan found no non-empty unknown extensions; positive values summarize skipped files with extensions that no language recognized.",
                "the field is absent in legacy indexes or before a current scanner stamps unknown-extension inventory metadata.",
                "Review `unknown_extension_files` and `unknown_extension_groups` in `cdidx status --json`, then update ignores or language support before rebuilding."),
            new(
                "head_freshness",
                "Compact HEAD freshness summary",
                "`state=fresh` means `status --check` proved the complete index matches the workspace; `state=fresh_but_incomplete` keeps workspace freshness distinct from failed-file coverage; without `--check`, `state=head_current` means only the runtime HEAD matched `indexed_head` (see `indexed_head_source`).",
                "`state=stale`, `state=stale_and_incomplete`, `state=head_changed`, `state=check_unavailable`, or `state=unchecked` means consumers should inspect `state_reason`, `index_complete`, and the nested head fields before trusting freshness-sensitive results.",
                "Use this summary for machine routing; `indexed_head_source=workspace_verified` identifies explicit whole-workspace proof. `latest_index` is retained only as unverified provenance fallback when no verified or legacy baseline exists, and `latest_index_head` always preserves latest-write provenance."),
            new(
                "index_matches_workspace",
                "Workspace freshness check",
                "`true` means `status --check` compared the current workspace with the index and found no missing, changed, deleted, or stale tracked files.",
                "`false` means the index does not fully match the workspace, and absence means the workspace check was not requested or could not run.",
                "Run `cdidx status --check --json` for mismatch details, then run `cdidx index <projectPath>` to refresh the index."),
            new(
                "path_case_sensitive",
                "Filesystem case sensitivity",
                "`true` means the indexed workspace path comparison is case-sensitive; `false` means case-insensitive.",
                "the field is absent on legacy indexes that predate the workspace case-sensitivity stamp.",
                "Run `cdidx index <projectPath>` with a current cdidx binary to stamp filesystem case sensitivity."),
        ])
        .Concat(StatusMemberExplainFields)
        .ToArray();
}
